version: "3.8"

services:
  nginx:
    build: .
    container_name: fazenda_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./private:/etc/nginx/private
      - ./conf.d:/etc/nginx/conf.d
